import ProjectCard from './ProjectCard';
import SectionTitle from './SectionTitle';

const Projects = () => {
  const projects = [
    {
      id: 1,
      title: "Career Advisor AI",
      description: "A real-time personalized career guidance assistant for South African students.",
      livePreview: "http://career-chat-ai.vercel.app/",
      thumbnail: "https://api.microlink.io/?url=http%3A%2F%2Fcareer-chat-ai.vercel.app%2F&overlay.browser=dark&screenshot=true&embed=screenshot.url",
      technologies: ["React", "Tailwind CSS", "Vercel", "Three.js"]
    },
    
    {
      id: 2,
      title: "Currency Converter",
      description: "FE Capstone Project featuring real-time currency conversion capabilities.",
      livePreview: "https://currency-xchange-x7lu.vercel.app/",
      thumbnail: "https://api.microlink.io/?url=https%3A%2F%2Fcurrency-xchange-x7lu.vercel.app%2F&overlay.browser=dark&screenshot=true&embed=screenshot.url",
      technologies: ["React", "ExchangeRate-API", "Tailwind CSS"]
    },
    {
      id: 3,
      title: "Client's Virtual Assistant Portfolio",
      description: "A modern and responsive personal portfolio showcasing my projects and skills.",
      livePreview: "https://va-portfolio-5e44c.web.app/",
      thumbnail: "https://api.microlink.io/?url=https%3A%2F%2Fva-portfolio-5e44c.web.app%2F&overlay.browser=dark&screenshot=true&embed=screenshot.url",
      technologies: ["React", "Tailwind CSS", "Firebase"]
  }
  //screenshot thumbnails generated by https://microlink.io/
];

  if (!projects?.length) {
    return (
      <div className="flex justify-center items-center min-h-[400px]">
        <p>No projects available</p>
      </div>
    );
  }

  return (
    <section className="max-w-6xl mx-auto py-12 px-4" id="projects">
      <SectionTitle title="Projects" />
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
        {projects.map((project) => (
          <ProjectCard 
            key={project.id}
            {...project}
          />
        ))}
      </div>
    </section>
  );
};

export default Projects;